# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    container_name: finances-db
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: hibernate
    ports:
      - 3666:3306
volumes:
    db_data: